---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services
# plex token user
# key: "NbvUKztPgxh1pBy2h4mF"

- Media:
    - Plex:
        icon: mdi-plex
        href: "https://plex.{{HOMEPAGE_VAR_DOMAIN}}:32400/web/index.html"
        description: Watch movies and TV shows
        widget:
          type: tautulli
          url: http://plex.{{HOMEPAGE_VAR_DOMAIN}}:8181
          key: "{{HOMEPAGE_VAR_TAUTULLI_TOKEN}}"
          enableUser: true
          showEpisodeNumber: true
    - Overseerr:
        # icon: overseerr
        icon: mdi-movie-open-plus
        href: https://overseer.{{HOMEPAGE_VAR_DOMAIN}}
        description: Request movies and TV shows
        widget:
          type: overseerr
          url: https://overseer.{{HOMEPAGE_VAR_DOMAIN}}
          key: "{{HOMEPAGE_VAR_OVERSEERR_TOKEN}}"
    - Jackett:
        # icon: jackett.png
        description: Indexer
        icon: mdi-radar
        href: http://jackett.{{HOMEPAGE_VAR_DOMAIN}}
        widget:
          type: jackett
          url: https://jacket.{{HOMEPAGE_VAR_DOMAIN}}
- Storage:
    - NAS:
        icon: si-files
        description: File storage
        href: https://nas.{{HOMEPAGE_VAR_DOMAIN}}
    - Default:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_NAS_MONITORING_URL}}"
          version: 4
          metric: "fs:/mnt/nas"
          chart: false
    - Books:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_NAS_MONITORING_URL}}"
          version: 4
          metric: "fs:/mnt/media/books"
          chart: false
    - Manga:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_NAS_MONITORING_URL}}"
          version: 4
          metric: "fs:/mnt/media/manga"
          chart: false
- Observability:
    - Pihole:
        icon: si-pi-hole
        href: https://pihole.{{HOMEPAGE_VAR_DOMAIN}}/admin
        widget:
          type: pihole
          url: https://pihole.{{HOMEPAGE_VAR_DOMAIN}}
          version: 5
          key: "{{HOMEPAGE_VAR_PIHOLE_TOKEN}}"
    - OPNSense:
        icon: si-opnsense
        href: "{{HOMEPAGE_VAR_OPNSENSE_URL}}"
        widget:
          type: opnsense
          url: "{{HOMEPAGE_VAR_OPNSENSE_URL}}"
          username: "{{HOMEPAGE_VAR_OPNSENSE_USERNAME}}"
          password: "{{HOMEPAGE_VAR_OPNSENSE_PASSWORD}}"
    - Proxmox:
        icon: si-proxmox
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        widget:
          type: proxmox
          url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
          username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
    - Tailscale:
        icon: si-tailscale
        href: https://login.tailscale.com/admin/machines
        namespace: "network"
        podSelector: >-
          app.kubernetes.io/instance in (
              tailscale-operator
              ingress-nginx-tailscale
          )
    - UptimeRobot:
        # icon: https://uptimerobot.com/favicon.ico
        icon: si-uptimekuma
        href: https://dashboard.uptimerobot.com
        widget:
          type: uptimerobot
          url: https://api.uptimerobot.com
          key: "{{HOMEPAGE_VAR_UPTIME_ROBOT_TOKEN}}"
    # - Prometheus:
    #     icon: si-prometheus
    #     widget:
    #       type: prometheus
    #       url: https://{{HOMEPAGE_VAR_PROMETHEUS_HOST}}.{{HOMEPAGE_VAR_DOMAIN}}
