---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- logo:
    icon: mdi-monitor-dashboard

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
    nodes:
      # show node specific statistics
      show: true
      cpu: true
      memory: true
      showLabel: true
# - resources:
#     cpu: true
#     memory: true
#     disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: md
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
