---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        #     supplementalGroups:
        #       - 65542 # gladius:external-services

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/calibre-web
              tag: 0.6.24@sha256:57fc39bbc7a49ee48f50b8691b47d768c130fd6e8569ec17bde051eae5beddd6
            env:
              CACHE_DIR: /cache
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M

    service:
      app:
        controller: calibre-web
        ports:
          http:
            port: 8083

    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Calibre Web
          gethomepage.dev/icon: si-calibreweb
          gethomepage.dev/description: Ebook Web Reader
          gethomepage.dev/group: Reading
          gethomepage.dev/widget.type: calibreweb
          gethomepage.dev/widget.url: https://ebooks.${SECRET_DOMAIN}
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_CALIBRE_WEB_USERNAME}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_CALIBRE_WEB_PASSWORD}}` }}"
        hosts:
          - host: &host ebooks.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "openebs-hostpath"
        size: 500m
        accessMode: ReadWriteOnce
        advancedMounts:
          calibre-web:
            app:
              - path: /config

      books:
        type: persistentVolumeClaim
        storageClass: manual
        volumeName: smb-books-pv
        size: 10Gi
        accessMode: ReadWriteMany
        globalMounts:
          - path: /data/books

      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
