---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invidious-secret
    template:
      engineVersion: v2
      data:
        # App
        INVIDIOUS_CONFIG: |
          database_url: postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local.:5432/invidious
          check_tables: true
          port: 3000
          domain: invidious.${SECRET_DOMAIN}
          hmac_key: {{ .HMAC_KEY }}
          signature_server: localhost:12999
          po_token: {{ .PO_TOKEN }}
          visitor_data: {{ .VISITOR_DATA }}
          https_only: true
          external_port: 443
          domain: invidious.${SECRET_DOMAIN}
          top_enabled: false
          popular_enabled: false
          related_videos: false
          statistics_enabled: false
          registration_enabled: false
          dark_mode: dark
          # Search
          default_user_preferences:
            default_home: ""
          quality: dash
          quality_dash: best

        # Postgres Init
        INIT_POSTGRES_DBNAME: invidious
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: invidious
