---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./csi-driver-smb.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./forgejo.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./tailscale.yaml
  - ./weave-gitops.yaml
  - ./xenitab.yaml
