apiVersion: v1
kind: Service
metadata:
  name: tautulli-external
spec:
  ports:
    - name: http
      port: 8181
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: tautulli-external
  labels:
    kubernetes.io/service-name: tautulli-external
addressType: IPv4
ports:
  - name: "http"
    appProtocol: http
    protocol: TCP
    port: 8181
endpoints:
  - addresses:
      - "${SECRET_PLEX_HOST}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli-internal
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "internal"
  rules:
    - host: &host tautulli.${SECRET_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tautulli-external
                port:
                  name: http
  tls:
    - hosts:
        - *host
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli-tailscale
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "tailscale"
  rules:
    - host: &host tautulli.${SECRET_TS_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tautulli-external
                port:
                  name: http
  tls:
    - hosts:
        - *host
