---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-init-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-init-db
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: "{{ .DB_NAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRES_CLUSTER_HOST }}"
        INIT_POSTGRES_USER: "{{ .DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: cloudnative-pg
