---
apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-init-db
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16
          envFrom:
            - secretRef:
                name: forgejo-init-db
