---
use_default_settings: true

server:
  limiter: true
  image_proxy: true
  method: GET # https://github.com/searxng/searxng/pull/3619
  public_instance: false

search:
  autocomplete: duckduckgo
  favicon_resolver: duckduckgo

general:
  instance_name: Search

ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: dark
  infinite_scroll: true
  results_on_new_tab: true
  hotkeys: vim

enabled_plugins:
  - Basic Calculator
  - Hash plugin
  - Hostnames plugin
  - Open Access DOI rewrite
  - Self Informations
  - Tracker URL remover
  - Unit converter plugin

hostnames:
  high_priority:
    - (.*)\/blog\/(.*)
    - (.*\.)?wikipedia.org$
    - (.*\.)?github.com$
    - (.*\.)?reddit.com$
    - (.*\.)?docker.com$
    - (.*\.)?nixos.org$
    - (.*\.)?archlinux.org$
    - (.*\.)?stackoverflow.com$
    - (.*\.)?askubuntu.com$
    - (.*\.)?superuser.com$
