---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: speedtest-tracker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: speedtest-tracker-secret
    template:
      engineVersion: v2
      data:
        # App
        APP_KEY: &appKey "{{ .SPEEDTEST_APP_KEY }}"
        DB_CONNECTION: pgsql
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_DATABASE: &dbName speedtest-tracker
        DB_USERNAME: &dbUser "{{ .SPEEDTEST_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .SPEEDTEST_POSTGRES_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: speedtest-tracker
    - extract:
        key: cloudnative-pg
