---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: openebs-hostpath
              globalMounts:
                - path: /config
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16"
            envFrom: &envFrom
              - secretRef:
                  name: speedtest-tracker-secret
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/speedtest-tracker
              tag: 0.21.2@sha256:7042d0d788e3fc09179f4ad445730fbe52cf73385ed80d52153ee7a2cbfcc28d
            envFrom: *envFrom
            env:
              SPEEDTEST_SCHEDULE: 0 * * * *
              DISPLAY_TIMEZONE: America/Vancouver
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 256Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: https://raw.githubusercontent.com/smbonn2005/homeops/main/icons/speedtest.png
          gethomepage.dev/name: Speedtest
          gethomepage.dev/group: "Glances"
          gethomepage.dev/widget.type: speedtest
          gethomepage.dev/widget.url: http://speedtest.default
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
