---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gotify-secret
    template:
      engineVersion: v2
      data:
        # App
        GOTIFY_DATABASE_DIALECT: postgres
        GOTIFY_DATABASE_CONNECTION: "host=postgres-16-rw.database.svc.cluster.local port=5432 user={{ .GOTIFY_POSTGRES_USER }} dbname=gotify password={{ .GOTIFY_POSTGRES_PASS }}"
        # Template
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_DATABASE: &dbName gotify
        DB_USERNAME: &dbUser "{{ .GOTIFY_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .GOTIFY_POSTGRES_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: gotify
    - extract:
        key: cloudnative-pg
