---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kaizoku
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kaizoku-secret
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: "postgresql://{{ .KAIZOKU_POSTGRES_USER }}:{{ .KAIZOKU_POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local:5432/kaizoku"
        REDIS_HOST: dragonfly.database.svc.cluster.local
        REDIS_PORT: "6379"
        # TODO: remove these from main container
        # Postgres Init
        INIT_POSTGRES_DBNAME: kaizoku
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .KAIZOKU_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .KAIZOKU_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: kaizoku
    - extract:
        key: cloudnative-pg
