# sha256:690f805322b11656ca62fb23c7b08439725a9ce9bc59e0e00f6b3c002bd7de44
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaizoku
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16"
            envFrom: &envFrom
              - secretRef:
                  name: kaizoku-secret
        containers:
          main:
            image:
              repository: ghcr.io/oae/kaizoku
              tag: v1.6.1@sha256:690f805322b11656ca62fb23c7b08439725a9ce9bc59e0e00f6b3c002bd7de44
            envFrom: *envFrom
            env:
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 256Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: si-wikibooks
          gethomepage.dev/name: Kaizoku
          gethomepage.dev/description: Manga downloader
          gethomepage.dev/group: Selfhosted
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "openebs-hostpath"
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
      logs:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        size: 1Gi
        globalMounts:
          - path: /logs
      manga:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path: /manga
        globalMounts:
          - path: /data
