---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb-driver
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: smb-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .SMB_USER }}"
        password: "{{ .SMB_PASSWORD }}"
  dataFrom:
    - extract:
        key: k8s-nas-user
