apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 30m
  releaseName: csi-driver-smb
  chart:
    spec:
      chart: csi-driver-smb
      version: "v1.17.0" # You can specify the version based on your requirements
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      tag: "latest"
