apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-books-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-volume
    volumeAttributes:
      source: "//10.26.26.4/books"
    nodeStageSecretRef:
      name: smb-secret
      namespace: default
    mountOptions:
      - vers=3.0
      - username=$(username)
      - password=$(password)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-books-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
