---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      homepage:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.9.12
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: homepage-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "dashboard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: docker.yaml
            path: /app/config/docker.yaml
            readOnly: true
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
            readOnly: true
          - subPath: services.yaml
            path: /app/config/services.yaml
            readOnly: true
          - subPath: settings.yaml
            path: /app/config/settings.yaml
            readOnly: true
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
            readOnly: true
      bookmarks:
        type: secret
        name: homepage-secret
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
            readOnly: true
    serviceAccount:
      create: true
      name: homepage
