---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: operator-oauth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client_id: "{{ .TAILSCALE_OPERATOR_OAUTH_CLIENT_ID }}"
        client_secret: "{{ .TAILSCALE_OPERATOR_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        # tailscale_operator_oauth_client_id, tailscale_operator_oauth_client_secret
        key: tailscale
