---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app komga
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      komga:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gotson/komga
              tag: 1.18.0@sha256:0997326496bb29cd6299ffab6cf1ca20490a3da3b240cd47c3c4e1aa67dbcf97
            env:
              TZ: ${TIMEZONE}
              SERVER_PORT: &port 8080
            resources:
              requests:
                cpu: 15m
                memory: 1Gi
              limits:
                memory: 4Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      main:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Reading
          gethomepage.dev/name: Komga
          # gethomepage.dev/icon: komga.png
          gethomepage.dev/icon: si-bookstack
          gethomepage.dev/description: Comic/Ebook Web Reader
          gethomepage.dev/widget.type: komga
          gethomepage.dev/widget.url: http://komga:8080
          gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_KOMGA_USERNAME}}` }}"
          gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_KOMGA_PASSWORD}}` }}"
          gethomepage.dev/pod-selector: >-
            app in (
              komga
            )
          # external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      tailscale:
        enabled: true
        className: nginx-tailscale
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "openebs-hostpath"
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
      manga:
        type: persistentVolumeClaim
        storageClass: manual
        volumeName: smb-manga-pv
        size: 100Gi
        accessMode: ReadWriteMany
        globalMounts:
          - path: /data/manga
